### ISSUE TITLE
Is the breakfast recipe ready?

### ISSUE THREAD

**Issue by halyreza2** [IntroToCode/CodeMates4_Spring23#11]
## 💬 Discussion topic

Are we done with the recipe?

## ❗ Potential issues
No recipe

## 👥 People to consult

@tzsidhu

**Comment by tzsidhu** [comment]
@halyreza2 Just completed the Receipe

**Comment by JE-codez** [comment]
Yes awesome job

**Comment by JE-codez** [comment]
please refer to the issue "WHAT SHOULD WE MAKE" for full discussion and acceptance criteria for breakfast and dinner recipes
