### ISSUE TITLE
WHAT SHOULD WE MAKE

### ISSUE THREAD

**Issue by JE-codez** [IntroToCode/CodeMates4_Spring23#3]
## 💬 Discussion topic

Hello team! We need to curate breakfast and lunch recipes. Lets use this issue to discuss and select two meal ideas.

## ❗ Potential issues

run out of ingredients
lack of consensus on meal plan
Allergies
Dietary restrictions

## 👥 People to consult

Tanaz, Soledad, Ella, Haider

## 📃 Details

Need to select recipes, define acceptance criteria, reach consensus and close out issue

**Comment by halyreza2** [comment]
Pancake for breakfast

**Comment by tzsidhu** [comment]
Easy peezy cereal

**Comment by tzsidhu** [comment]
False close

**Comment by JE-codez** [comment]
We decided to make pancakes for breakfast and spaghetti for dinner

**Comment by JE-codez** [comment]
Acceptance criteria for pancakes: must include a topping / mix-in, must be ready in under 30 minutes, must serve 5+ people

**Comment by JE-codez** [comment]
Acceptance criteria for spaghetti: must include pasta, must include a sauce, must be ready in under 2 hours, must serve 5+ people, must include a vegetable
